name: Deploy to heroku.

on:
  push:
    branches: [heroku]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Build, Push and Release a Docker container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with: 
          email: "cgr28@njit.edu"
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "maze-creator-and-solver"